import Foundation
import privacycommandCLIKit

/// `privacycommand completion <shell>` — print a tab-completion script.
/// The scripts themselves are generated by `ShellCompletion`.
enum CompletionCommand {

    static let help = """
    usage: privacycommand completion <zsh|bash|fish>

    Print a tab-completion script for your shell. A Homebrew install sets these
    up for you. Otherwise, add one of these:

      zsh    in ~/.zshrc, after `autoload -Uz compinit && compinit`:
               eval "$(privacycommand completion zsh)"
      bash   in ~/.bash_profile:
               eval "$(privacycommand completion bash)"
      fish   run once:
               privacycommand completion fish > ~/.config/fish/completions/privacycommand.fish

    Completes subcommands, options, installed app names, risk tiers, and the
    outdated casks `preview` and `upgrade` would look at.
    """

    static func run(_ argv: [String]) -> Never {
        guard let first = argv.first else { die("no shell given.\n\n" + help, code: 2) }
        if first == "-h" || first == "--help" {
            print(help)
            exit(0)
        }
        guard argv.count == 1 else {
            die("completion takes one shell (extra argument: \(argv[1]))", code: 2)
        }
        guard let shell = ShellCompletion.Shell(rawValue: first) else {
            die("unknown shell: \(first)  (one of: zsh, bash, fish)", code: 2)
        }
        print(ShellCompletion.script(for: shell), terminator: "")
        exit(0)
    }
}
